[profile.default]
solc = "0.8.28"
block_timestamp = 1_738_368_000 # Feb 1, 2025 at 00:00 GMT
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache/forge'
evm_version = "shanghai"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [
	{ access = "read", path =  "out"},
	{ access = "read", path =  "./lib/hypercerts-protocol/contracts/src/deployments"}]
optimizer = true
optimizer_runs = 200

[etherscan]
sepolia = { key = "${API_KEY_ETHERSCAN}" }
base = { key = "${API_KEY_BASESCAN}" }
optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
arbitrum = { key = "${API_KEY_ARBISCAN}" }
celo = { key = "${API_KEY_CELOSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
base-sepolia = "https://base-sepolia.infura.io/v3/${API_KEY_INFURA}"
arbitrum-sepolia = "https://arbitrum-sepolia.infura.io/v3/${API_KEY_INFURA}"
optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
base = "https://base-mainnet.infura.io/v3/${API_KEY_INFURA}"
celo = "https://celo-mainnet.infura.io/v3/${API_KEY_INFURA}"